"""Solver tolerances and pixel dimensions at the calibration resolution."""
from .ballistics import REFERENCE_WIDTH

REFLECTION_LOW_POWER_MARGIN = 2
REFLECTION_MIN_INCIDENCE = 0.08
INTEGER_ANGLE_RADIUS = 2
PORTAL_TRIGGER_RADIUS_SCALE = 0.90
PORTAL_AVOID_MARGIN_AT_REFERENCE = 5.0
TARGET_ACCEPT_RADIUS_AT_REFERENCE = 24.0
LINE_ENDPOINT_MARGIN_AT_REFERENCE = 6.0
MISS_TIE_THRESHOLD_AT_REFERENCE = 2.0
COLLISION_TIME_EPS = 1e-5
ROOT_IMAG_EPS = 1e-7
EQUATION_RESIDUAL_TOL = 1e-5
CIRCLE_SIDE_EPS = 1e-5
MAX_FLIGHT_TIME = 12.0
N_LINE_SCAN = 32
N_CIRCLE_SCAN = 64


def portal_trigger_radius(portal):
    return portal.radius * PORTAL_TRIGGER_RADIUS_SCALE


def portal_avoid_radius(portal, scale):
    return portal.radius + PORTAL_AVOID_MARGIN_AT_REFERENCE * scale
